// <auto-generated />
using ASPNETPT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNETPT.Migrations
{
    [DbContext(typeof(BtcContext))]
    partial class BtcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNETPT.Models.BtCprop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Ask");

                    b.Property<double>("Bid");

                    b.Property<string>("Date");

                    b.Property<string>("Name");

                    b.Property<double>("Rate");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Btcs");
                });
#pragma warning restore 612, 618
        }
    }
}
